211229.181712.HKT improve Makefile.common by introducing ``|| :" to avoid errors when cleaning fails
Former-commit-id: cefdc27a2a6295c2e85bc01fcc1b9a258ca335fd [formerly 8dc942d3932d0f1490b0bd9f9108516fe25b8b67]
Former-commit-id: a56d8e70937558176954820d38905c5c9a82ab14

diff --git a/fsrc/tests/makefiles/Makefile.common b/fsrc/tests/makefiles/Makefile.common
--- a/fsrc/tests/makefiles/Makefile.common
+++ b/fsrc/tests/makefiles/Makefile.common
@@ -473,7 +473,7 @@ $(TESTS_C) $(TESTS_INT_C):
 	@bash $(CHCKTST) --warning "$(LOG_DIR)/$@.log"
 	@printf "$@ ends at $(shell date +%Y.%m.%d_%H.%M.%S).\n" | tee -a "$(LOG_DIR)/$@.log"
 	@cat "$(LOG_DIR)/$@.log" >> "$(LOG_DIR)/$(shell echo $@ | sed "s/_.*//").log"
-	@rm "$(LOG_DIR)/$@.log"
+	@rm "$(LOG_DIR)/$@.log" || :
 	@$(MAKE) cleanmisc
 
 # Make the binary corresponding to %_tst_c, but do not execute it.
@@ -519,7 +519,7 @@ $(TESTS_C) $(TESTS_INT_C):
 	@bash $(CHCKTST) --warning "$(LOG_DIR)/$@.log"
 	@printf "$@ ends at $(shell date +%Y.%m.%d_%H.%M.%S).\n" | tee -a "$(LOG_DIR)/$@.log"
 	@cat "$(LOG_DIR)/$@.log" >> "$(LOG_DIR)/$(shell echo $@ | sed "s/_.*/_c/").log"
-	@rm "$(LOG_DIR)/$@.log"
+	@rm "$(LOG_DIR)/$@.log" || :
 	@$(MAKE) cleanmisc
 	@touch $@
 # Without the last line, 9test_c is always remade when making 9test even if 9test_c is up
@@ -569,24 +569,25 @@ header_%: source_%
 
 ####################################################################################################
 # Cleaning up.
+# ":" means do nothing in bash. We can use "COMMAND || :" to avoid errors when COMMAND fails.
 cleanbin:
 	@printf "\nCleaning up the binaries ...\n"
-	@rm -f *_tst_c
-	@rm -f *_test_c
+	@rm -f *_tst_c || :
+	@rm -f *_test_c || :
 	@printf "Done.\n"
 
 cleanmisc:
 	@printf "\nCleaning up miscellaneous files ...\n"
-	@rm -f *.o *.mod *.dbg *.cmdx *.cmod *.ilm *.stb *.out *__genmod.f90
-	@rm -f *_output.txt
+	@rm -f *.o *.mod *.dbg *.cmdx *.cmod *.ilm *.stb *.out *__genmod.f90 || :
+	@rm -f *_output.txt || :
 	@printf "Done.\n"
 
 cleansrc:
 	@printf "\nCleaning up the source code ...\n"
 	@for ITEM in $(COMMON) $(SOLVER) $(TESTSUITE) $(DRIVER_SRC) ; do  \
 		if [ `ls -1 "$$ITEM" 2>/dev/null | wc -l ` -gt 0 ] ; \
-			then mkdir -p $(TRASH_DIR); rm -rf $(TRASH_DIR)/"$$ITEM"; \
-			mv "$$ITEM" $(TRASH_DIR) > /dev/null 2>&1; \
+			then mkdir -p $(TRASH_DIR) && rm -rf $(TRASH_DIR)/"$$ITEM" || : ; \
+			mv "$$ITEM" $(TRASH_DIR) > /dev/null 2>&1 || : ; \
 		fi ; \
 	done
 	@printf "Done.\n"
@@ -594,4 +595,4 @@ cleansrc:
 clean: cleanbin cleanmisc cleansrc
 
 cleanall: clean
-	rm -rf $(TRASH_DIR) $(LOG_DIR)
+	rm -rf $(TRASH_DIR) $(LOG_DIR) || :
