260208.095051.CET [skip ci] Makefile.common: check compiler version before making the test

diff --git a/fortran/tests/makefiles/Makefile.common b/fortran/tests/makefiles/Makefile.common
--- a/fortran/tests/makefiles/Makefile.common
+++ b/fortran/tests/makefiles/Makefile.common
@@ -922,6 +922,10 @@ $(TESTS_C) $(TESTS_INT_C):
 		-DPRIMA_INTEGER_KIND=$(IK) -DPRIMA_REAL_PRECISION=$(RP) -DPRIMA_QP_AVAILABLE=$(QPAVLB) -DPRIMA_TESTDIM=\"'$(TESTDIM)'\")
 	$(eval EXTRA_FLAGS := $(shell if [[ -z "$(TESTSEED)" ]] ; then echo "$(EXTRA_FLAGS)"; else echo "$(EXTRA_FLAGS) -DPRIMA_TESTSEED=$(TESTSEED)"; fi))
 	$(eval SRC := $(shell if echo $@ | grep -q "9test"; then echo $(SRC_NO_TEST) ; else echo $(SRC) ; fi))
+	$(eval FC := $(shell cut -d' ' -f1 <<< "$(FCO)"))
+	@echo "Compiler: $(FC)"
+	@$(FC) --version 2>&1 | grep -v "\-\-version\|usage" || true  # Print the compiler version, but do not fail if the compiler does not support `--version`
+	@echo ""
 	(if echo $@ | grep -q '9test'; then \
 		if [[ -n '$(FFLAGSO)' ]] ; then \
 			if [[ '$(FFLAGSO)' = '-fast' ]] ; then \
