240309.215008.HKT update .mygit/pre-committ

diff --git a/.mygit/hooks/pre-commit b/.mygit/hooks/pre-commit
--- a/.mygit/hooks/pre-commit
+++ b/.mygit/hooks/pre-commit
@@ -3,8 +3,9 @@
 # Commit submodules
 ROOTDIR=$(git rev-parse --show-toplevel)
 for SUBMODULE in $(git submodule status | awk '{print $2}'); do
-    echo "Committing $SUBMODULE"
-    cd "$SUBMODULE" || (printf "Error: submodule %s not found\n" "$SUBMODULE" && exit 1)
+    SMDIR="$ROOTDIR/$SUBMODULE"
+    echo "Committing $SUBMODULE ..."
+    cd "$SMDIR" || (printf "Error: submodule %s not found\n" "$SMDIR" && exit 1)
     git add -A
     git commit -m "Update $SUBMODULE"
 done
