230615.021224.CST fix https://github.com/libprima/prima/issues/30 , modify `flint` and `mlint` for more extensive linting

diff --git a/fortran/common/mlint b/fortran/common/mlint
--- a/fortran/common/mlint
+++ b/fortran/common/mlint
@@ -76,10 +76,6 @@ while [[ -n "$1" ]]; do
     shift
 done
 
-# The default Fortran compiler options.
-FFLAGS=''
-# We export FFLAGS, which will be referred to by the Makefiles.
-export FFLAGS
 
 # The directory where this script resides. It is the solver's directory.
 SOLVER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@@ -137,7 +133,10 @@ printf "Tests to make:%s\n\n" "$COMP_LIST"
 
 for COMP in $COMP_LIST; do
     if [[ $TEST_ALL == 'Y' && $ARM32 != 'Y' ]] ; then
-        make  "$COMP"test."$SOLVER"
+        for FLG in -g -O1 -O2 -O3 -fast ; do
+            printf "%s\t" "$FLG"
+            export FFLAGS=$FLG && make "$COMP"test."$SOLVER"
+        done
     else
        if [[ $COMP == 'f' || $COMP == 'v' || $COMP == 'd' || $COMP == 'x' || $ARM32 == 'Y' ]] ; then
             TESTS="i2_r4_d1 i8_r4_d0"
@@ -145,26 +144,30 @@ for COMP in $COMP_LIST; do
             TESTS="i2_r16_d1 i8_r4_d0"
         fi
         for TEST in $TESTS ; do
-            INFO="$(make "$COMP"test_"$TEST"_tst."$SOLVER" 2>&1 \
-                | grep -v "binary\ file\ matches" \
-                | grep -i "starts\|warning\|error\|info\|abort\|invalid\|violation\|fault\|illegal\|fail\|questionable\|remark\|attention\|Could\ not\ resolve" \
-                | grep -vi "[0-9]\s*warning\|[0-9]\s*error\|[0-9]\s*info\|infos.f90\|information\|xhist, info)\|--warning\|--error" \
-                | grep -vi "pedantic-errors\|Werror\|warn\ errors\|diag-error-limit\|colour=error\|rounding\ error\|constraint\ violation" \
-                | grep -vi "INFO_DFT\|==\s*info\|errorid\|errormsg" \
-                | grep -vi "\[xopt, fopt, info, nf, xhist, fhist\] = FUNCTION_NAME" \
-                | grep -v "^- \|^| \|^\* \|^+ \|^X \|\# " \
-                )"
-            echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|abort\|invalid\|violation\|fault\|illegal\|fail\|questionable\|remark\|attention\|Could\ not\ resolve"
-            if echo "$INFO" | grep -iq "error\|abort\|invalid\|violation\|fault\|illegal\|fail\|Could\ not\ resolve" ; then
-                if [[ -f "$TEST_LOG_DIR"/"$COMP"test_"$TEST"_tst.log ]] ; then
-                    LOGFILE="$COMP"test_"$TEST"_tst.log
-                else
-                    LOGFILE="$COMP"test.log
+            for FLG in -g -O2 -fast ; do
+                printf "%s\t" "$FLG"
+                export FFLAGS=$FLG
+                INFO="$(make "$COMP"test_"$TEST"_tst."$SOLVER" 2>&1 \
+                    | grep -v "binary\ file\ matches" \
+                    | grep -i "starts\|warning\|error\|info\|abort\|invalid\|violation\|fault\|illegal\|fail\|questionable\|remark\|attention\|Could\ not\ resolve" \
+                    | grep -vi "[0-9]\s*warning\|[0-9]\s*error\|[0-9]\s*info\|infos.f90\|information\|xhist, info)\|zmat, info)\|--warning\|--error" \
+                    | grep -vi "pedantic-errors\|Werror\|warn\ errors\|diag-error-limit\|colour=error\|rounding\ error\|constraint\ violation" \
+                    | grep -vi "INFO_DFT\|==\s*info\|errorid\|errormsg" \
+                    | grep -vi "\[xopt, fopt, info, nf, xhist, fhist\] = FUNCTION_NAME" \
+                    | grep -v "^- \|^| \|^\* \|^+ \|^X \|\# " \
+                    )"
+                echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|abort\|invalid\|violation\|fault\|illegal\|fail\|questionable\|remark\|attention\|Could\ not\ resolve"
+                if echo "$INFO" | grep -iq "error\|abort\|invalid\|violation\|fault\|illegal\|fail\|Could\ not\ resolve" ; then
+                    if [[ -f "$TEST_LOG_DIR"/"$COMP"test_"$TEST"_tst.log ]] ; then
+                        LOGFILE="$COMP"test_"$TEST"_tst.log
+                    else
+                        LOGFILE="$COMP"test.log
+                    fi
+                    mv "$TEST_LOG_DIR"/"$LOGFILE" "$SOLVER_LOG_DIR"
+                    cat "$SOLVER_LOG_DIR"/"$LOGFILE"
+                    exit 2
                 fi
-                mv "$TEST_LOG_DIR"/"$LOGFILE" "$SOLVER_LOG_DIR"
-                cat "$SOLVER_LOG_DIR"/"$LOGFILE"
-                exit 2
-            fi
+            done
         done
     fi
     mv "$TEST_LOG_DIR"/"$COMP"test*.log "$SOLVER_LOG_DIR" 2>/dev/null || true
