220203.190742.HKT update savefilt.f90; revise the test Makefiles to conduct the tests in /tmp
Former-commit-id: 122e9be9bcf0138c0e0977c89bbe5a88d10ab277 [formerly cc17b8faaf95d3fa34fd4cc3ff36e250426b4ab1]
Former-commit-id: 8e445668b2fbd8216c5280ba141844b2609ed2b1

diff --git a/fsrc/common/flint b/fsrc/common/flint
--- a/fsrc/common/flint
+++ b/fsrc/common/flint
@@ -19,23 +19,34 @@ fi
 
 # The directory where this script resides. It is the solver's directory.
 SOLVER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-# The log directory in the solver's directory.
-SOLVER_LOG_DIR="$SOLVER_DIR"/flog
 
 # The solver's name.
 SOLVER=$(basename "$SOLVER_DIR")
 
+# The log directory in the solver's directory.
+SOLVER_LOG_DIR="$SOLVER_DIR"/flog
+
+# Root directory of this project.
+ROOT_DIR=../..
+
 # The testing directory.
-TEST_DIR="$SOLVER_DIR"/../tests
+TMP_DIR=/tmp
+TEST_ROOT="$TMP_DIR"/neupdfo
+TEST_DIR="$TEST_ROOT"/fsrc/tests
+TEST_SOLVER_DIR="$TEST_DIR"/test."$SOLVER"
+
 # The log directory in the testing directory.
-TEST_LOG_DIR="$TEST_DIR"/test."$SOLVER"/log
+TEST_LOG_DIR="$TEST_SOLVER_DIR"/log
+
+# The checktest script
+CHCKTST="$TEST_DIR"/checktest
 
 # Remove the old logs.
 mkdir -p "$SOLVER_LOG_DIR"
 rm -f "$SOLVER_LOG_DIR"/*test*.log
 
 # Conduct the test.
-cd "$TEST_DIR" || exit 1
+cd "$ROOT_DIR"/fsrc/tests || exit 1
 
 # Make clean (old logs in $SOLVER_LOG_DIR have been cleaned up in the above).
 printf "\nCleaning up ... "
@@ -95,14 +106,14 @@ for COMP in $COMP_LIST; do
     mv "$TEST_LOG_DIR"/"$COMP"test*.log "$SOLVER_LOG_DIR"
 done
 
-make clean."$SOLVER"
+make cleanall."$SOLVER"
 
 # Check the logfiles
 LOGFILES=("$SOLVER_LOG_DIR"/*test*.log)
 if [[ "$TEST_ALL" == "Y" ]] ; then
     for LOGFILE in "${LOGFILES[@]::${#LOGFILES[@]}}" ; do
         printf "\nChecking %s ...\n" "$LOGFILE"
-        INFO="$(bash "$TEST_DIR"/checktest --warnerror "$LOGFILE")"
+        INFO="$(bash "$CHCKTST" --warnerror "$LOGFILE")"
         printf "%s" "$INFO"
         printf "\nDone!\n"
         if [[ -n "$INFO" ]] ; then
@@ -113,8 +124,8 @@ if [[ "$TEST_ALL" == "Y" ]] ; then
 else
     for LOGFILE in "${LOGFILES[@]::${#LOGFILES[@]}-1}" ; do
         printf "\nChecking %s ...\n" "$LOGFILE"
-        bash "$TEST_DIR"/checktest --error "$LOGFILE"  # Will lead to failure in case of error logged
-        INFO="$(bash "$TEST_DIR"/checktest --warning "$LOGFILE")"
+        bash "$CHCKTST" --error "$LOGFILE"  # Will lead to failure in case of error logged
+        INFO="$(bash "$CHCKTST" --warning "$LOGFILE")"
         printf "%s" "$INFO"
         printf "\nDone!\n"
         if [[ -n "$INFO" ]] ; then
@@ -128,8 +139,8 @@ else
     # No pause needed for the last logfile.
     LOGFILE="${LOGFILES[-1]}"  # The last logfile; it needs Bash 4.x.
     printf "\nChecking %s ...\n" "$LOGFILE"
-    bash "$TEST_DIR"/checktest --error "$LOGFILE"
-    bash "$TEST_DIR"/checktest --warning "$LOGFILE"
+    bash "$CHCKTST" --error "$LOGFILE"
+    bash "$CHCKTST" --warning "$LOGFILE"
     printf "%s" "$INFO"
     printf "\nDone!\n\n"
 fi
