220109.210406.HKT revise the Makefile and lint for 9test

diff --git a/fsrc/common/lint b/fsrc/common/lint
--- a/fsrc/common/lint
+++ b/fsrc/common/lint
@@ -28,7 +28,7 @@ TEST_LOG_DIR="$TEST_DIR"/test."$SOLVER"/log
 
 # Remove the old logs.
 mkdir -p "$SOLVER_LOG_DIR"
-rm -f "$SOLVER_LOG_DIR"/*test*_c.log
+rm -f "$SOLVER_LOG_DIR"/*test*.log
 
 # Conduct the test.
 cd "$TEST_DIR" || exit 1
@@ -54,11 +54,11 @@ for COMPILER in $COMPILER_LIST; do
         fi
         for TEST in $TESTS ; do
             INFO="$(make "$COMPILER"test_"$TEST"_tst_c."$SOLVER" \
-                | grep -i "starts\|warning\|error\|info\|fail\|abort\|questionable\|remark" \
+                | grep -i "starts\|warning\|error\|info\|fail\|abort\|questionable\|remark\|attention" \
                 | grep -vi "[0-9]\s*warning\|[0-9]\s*error\|[0-9]\s*info\|info.f90\|information\|--warning\|--error" \
                 | grep -v "^- \|^| \|^\* \|^+ \|^X \|\# " \
                 )"
-            echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|fail\||abort\|questionable\|remark"
+            echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|fail\||abort\|questionable\|remark\|attention"
             if echo "$INFO" | grep -iq "error\|fail\|abort" ; then
                 if [[ -f "$TEST_LOG_DIR"/"$COMPILER"test_"$TEST"_tst_c.log ]] ; then
                     LOGFILE="$COMPILER"test_"$TEST"_tst_c.log
