211228.205258.HKT revise datetime.f90
Former-commit-id: 59abe5d3f10182f082e984ba3a062459131d1742 [formerly 8fa36ec27453447a26960598a0c9022fde9380c6]
Former-commit-id: 1850b08e6f893c4a91633d78eccd00101425f50e

diff --git a/fsrc/common/lint b/fsrc/common/lint
--- a/fsrc/common/lint
+++ b/fsrc/common/lint
@@ -36,7 +36,7 @@ for COMPILER in $COMPILER_LIST; do
     fi
     for TEST in $TESTS ; do
         INFO="$(make "$COMPILER"test_"$TEST"_tst_c."$SOLVER" \
-            | grep -i "starts\|warning\|error\|info\|fail|abort" \
+            | grep -i "starts\|warning\|error\|info\|fail\|abort\|questionable" \
             | grep -vi "[0-9]\s*warning\|[0-9]\s*error\|[0-9]\s*info\|info.f90\|information\|--warning\|--error" \
             | grep -v "interpolation error" \
             | grep -v "WARNING --  When --chk x is specified" \
@@ -53,7 +53,7 @@ for COMPILER in $COMPILER_LIST; do
         elif [[ "$COMPILER" == "n" ]] ; then
             INFO="$(echo "$INFO" | grep -vi "Expression in IF construct is constant")"
         fi
-        echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|fail|abort"
+        echo "$INFO" | grep -i --color "starts\|warning\|error\|info\|fail\||abort\|questionable"
         if echo "$INFO" | grep -iq "error\|fail\|abort" ; then
             if [[ -f "$TEST_LOG_DIR"/"$COMPILER"test_"$TEST"_tst_c.log ]] ; then
                 LOGFILE="$COMPILER"test_"$TEST"_tst_c.log
