240220.233942.HKT minor revision

diff --git a/.github/workflows/cmake_mac_nagfor.yml b/.github/workflows/cmake_mac_nagfor.yml
--- a/.github/workflows/cmake_mac_nagfor.yml
+++ b/.github/workflows/cmake_mac_nagfor.yml
@@ -30,7 +30,6 @@ jobs:
       fail-fast: false
       matrix:
         cc: [gcc, clang]
-        fc: [nagfor]
 
 
     steps:
@@ -64,17 +63,13 @@ jobs:
           export CC=${{ matrix.cc }}
           export CFLAGS='-Wall -Wextra -Wpedantic -Werror'
 
-          export FC=${{ matrix.fc }}
-          if [[ "$FC" == "nagfor" ]] ; then
-              source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
-              export FFLAGS='-fpp -nan -ieee=stop -recursive -gline -u -C -C=alias -C=dangling -C=intovf -kind=unique -Warn=constant_coindexing -Warn=subnormal'
-              # Zaikun 20240121: With gcc 13.2 or AppleClang 1.5.0 and nagfor 7.1.7143, if '-C=undefined'
-              # is included in FFLAGS, then the C tests will encounter a segmentation fault, although
-              # the Fortran tests work correctly.
-              #export FFLAGS='-fpp -nan -ieee=stop -recursive -gline -u -C -C=alias -C=dangling -C=intovf -C=undefined -kind=unique -Warn=constant_coindexing -Warn=subnormal'
-          else
-              export FFLAGS='-Wall -Wextra -Wpedantic -Werror -fimplicit-none -frecursive -fcheck=all -fstack-check -Wno-function-elimination'
-          fi
+          export FC="nagfor"
+          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
+          export FFLAGS='-fpp -nan -ieee=stop -recursive -gline -u -C -C=alias -C=dangling -C=intovf -kind=unique -Warn=constant_coindexing -Warn=subnormal'
+          # Zaikun 20240121: With gcc 13.2 or AppleClang 1.5.0 and nagfor 7.1.7143, if '-C=undefined'
+          # is included in FFLAGS, then the C tests will encounter a segmentation fault, although
+          # the Fortran tests work correctly.
+          #export FFLAGS='-fpp -nan -ieee=stop -recursive -gline -u -C -C=alias -C=dangling -C=intovf -C=undefined -kind=unique -Warn=constant_coindexing -Warn=subnormal'
 
           cmake --version
           cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=. -LAH -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_Fortran_FLAGS="${FFLAGS}" .
