240219.013116.HKT use github-hosted runner in cmake_mac.yml

diff --git a/.github/workflows/cmake_mac_nagfor.yml b/.github/workflows/cmake_mac_nagfor.yml
--- a/.github/workflows/cmake_mac_nagfor.yml
+++ b/.github/workflows/cmake_mac_nagfor.yml
@@ -1,4 +1,4 @@
-name: CMake build, macOS ARM64
+name: CMake build, macOS ARM64, nagfor
 
 on:
   # Trigger the workflow on push or pull request
@@ -24,14 +24,13 @@ run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual run {0}
 jobs:
 
   cmake:
-    runs-on: ${{ matrix.os }}
+    runs-on: [self-hosted, macOS, ARM64]
     continue-on-error: true
     strategy:
       fail-fast: false
       matrix:
-        os: [macos-14]
         cc: [gcc, clang]
-        fc: [gfortran]
+        fc: [nagfor]
 
 
     steps:
@@ -59,11 +58,6 @@ jobs:
       - name: Miscellaneous setup
         run: bash .github/scripts/misc_setup
 
-      - name: Set up Fortran for macOS 14
-        run: |
-          brew install gcc && which gcc && gcc --version
-          brew install gfortran && which gfortran && gfortran --version
-
       - name: Build
         shell: bash
         run: |
@@ -71,7 +65,16 @@ jobs:
           export CFLAGS='-Wall -Wextra -Wpedantic -Werror'
 
           export FC=${{ matrix.fc }}
-          export FFLAGS='-Wall -Wextra -Wpedantic -Werror -fimplicit-none -frecursive -fcheck=all -fstack-check -Wno-function-elimination'
+          if [[ "$FC" == "nagfor" ]] ; then
+              source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
+              export FFLAGS='-fpp -nan -ieee=stop -recursive -gline -u -C -C=alias -C=dangling -C=intovf -kind=unique -Warn=constant_coindexing -Warn=subnormal'
+              # Zaikun 20240121: With gcc 13.2 or AppleClang 1.5.0 and nagfor 7.1.7143, if '-C=undefined'
+              # is included in FFLAGS, then the C tests will encounter a segmentation fault, although
+              # the Fortran tests work correctly.
+              #export FFLAGS='-fpp -nan -ieee=stop -recursive -gline -u -C -C=alias -C=dangling -C=intovf -C=undefined -kind=unique -Warn=constant_coindexing -Warn=subnormal'
+          else
+              export FFLAGS='-Wall -Wextra -Wpedantic -Werror -fimplicit-none -frecursive -fcheck=all -fstack-check -Wno-function-elimination'
+          fi
 
           cmake --version
           cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=. -LAH -DCMAKE_C_FLAGS="${CFLAGS}" -DCMAKE_Fortran_FLAGS="${FFLAGS}" .
