230617.230005.CST mlint on GitHb hosted runners

diff --git a/.github/workflows/lint_hosted.yml b/.github/workflows/lint_hosted.yml
--- a/.github/workflows/lint_hosted.yml
+++ b/.github/workflows/lint_hosted.yml
@@ -1,9 +1,9 @@
-name: Lint the Fortran code on GitHub hosted runners
+name: Lint the Fortran code and the MEX gateways on GitHub hosted runners
 
 on:
   # Trigger the workflow on push or pull request
   push:
-  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
+  pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
   # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
   schedule:
     - cron: '0 17 * * *'
@@ -19,6 +19,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        linter: [flint, mlint]
         solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
 
     steps:
@@ -57,7 +58,24 @@ jobs:
       - name: Install Flang
         run: bash .github/scripts/install_flang
 
+      - name: Cache MATLAB
+        if: ${{ matrix.linter == 'mlint' }}
+        uses: actions/cache@v3.3.1
+        with:
+          path: ${{ runner.tool_cache }}/MATLAB
+          key: ${{ matrix.os }}
+
+      - name: Set up MATLAB
+        if: ${{ matrix.linter == 'mlint' }}
+        uses: matlab-actions/setup-matlab@v2-beta
+        with:
+          release: latest
+
       - name: Conduct the test
         run: |
           type gfortran ifort ifx aflang g95 nvfortran sunf95 flang
-          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./flint --all
+          if [[ ${{ matrix.linter }} == "mlint" ]] ; then
+              printf "Copy fintrf to %s ...\n\n" "$ROOT_DIR"/fortran/common
+              cp $(dirname $(which matlab))/../extern/include/fintrf.h "$ROOT_DIR"/fortran/common && printf "Succeed!\n\n" || printf "Fail!\n\n" && exit 2
+          fi
+          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./${{ matrix.linter }} --all
diff --git a/.github/workflows/lint_nagfor.yml b/.github/workflows/lint_nagfor.yml
--- a/.github/workflows/lint_nagfor.yml
+++ b/.github/workflows/lint_nagfor.yml
@@ -1,4 +1,4 @@
-name: Lint the Fortran code and the MEX gateways
+name: Lint the Fortran code and the MEX gateways with nagfor
 
 on:
   # Trigger the workflow on push or pull request
@@ -14,8 +14,8 @@ on:
 jobs:
 
   test:
-    name: Lint the Fortran code and the MEX gateways
-    runs-on: [self-hosted, linter]
+    name: Lint the Fortran code and the MEX gateways with nagfor
+    runs-on: [self-hosted, nagfor]
     strategy:
       fail-fast: false
       matrix:
@@ -35,10 +35,10 @@ jobs:
         run: |
           source ~/.bashrc
           export PATH=$PATH:"~/local/bin"
-          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
+          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n" && exit 2
           cd "$ROOT_DIR"/fortran/${{ matrix.solver }}
           if [[ $(($(date +%d) % 2)) == 0 ]] ; then
-              bash ./flint --all
+              bash ./flint -n
           else
-              bash ./mlint --all
+              bash ./mlint -n
           fi
