260205.122142.CET [skip ci] allow `sudo apt update` to fail by adding `|| true`

diff --git a/.github/workflows/lint_hosted.yml b/.github/workflows/lint_hosted.yml
--- a/.github/workflows/lint_hosted.yml
+++ b/.github/workflows/lint_hosted.yml
@@ -32,8 +32,8 @@ jobs:
 
     steps:
 
-      - name: Run `sudo apt update -y`
-        run: sudo apt update -y  # Otherwise, free-disk-space or other actions relying on `apt` may fail
+      - name: Run `sudo apt update`
+        run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
 
       - name: Free disk space
         uses: jlumbroso/free-disk-space@main
@@ -83,7 +83,8 @@ jobs:
           # Remove MATLAB, or the runner will run out of space.
           sudo rm -rf "$MATLABROOT"/* || exit 4
           # mlint uses `locate` to find fintrf.h
-          sudo apt update -y && sudo apt install plocate -y && sudo updatedb
+          sudo apt update || true
+          sudo apt install plocate -y && sudo updatedb
           locate '/extern/include/fintrf.h' || exit 5
 
       - name: Install AOCC
diff --git a/.github/workflows/profile_rescue_idz_modernized.yml b/.github/workflows/profile_rescue_idz_modernized.yml
--- a/.github/workflows/profile_rescue_idz_modernized.yml
+++ b/.github/workflows/profile_rescue_idz_modernized.yml
@@ -37,8 +37,8 @@ jobs:
       - name: Get the solver name
         run:  echo "SOLNAME=$(echo ${{ matrix.solver }} | cut -c1-6)" >> $GITHUB_ENV
 
-      - name: Run `sudo apt update -y`
-        run: sudo apt update -y  # Otherwise, free-disk-space or other actions relying on `apt` may fail
+      - name: Run `sudo apt update`
+        run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
 
       - name: Free disk space
         uses: jlumbroso/free-disk-space@main
diff --git a/.github/workflows/stress_test_fortran.yml b/.github/workflows/stress_test_fortran.yml
--- a/.github/workflows/stress_test_fortran.yml
+++ b/.github/workflows/stress_test_fortran.yml
@@ -45,9 +45,9 @@ jobs:
 
     steps:
 
-      - name: Run `sudo apt update -y`
+      - name: Run `sudo apt update`
         if: startsWith(matrix.os, 'ubuntu')
-        run: sudo apt update -y  # Otherwise, free-disk-space or other actions relying on `apt` may fail
+        run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
 
       - name: Free disk space
         if: startsWith(matrix.os, 'ubuntu')
diff --git a/.github/workflows/test_g95.yml b/.github/workflows/test_g95.yml
--- a/.github/workflows/test_g95.yml
+++ b/.github/workflows/test_g95.yml
@@ -31,8 +31,8 @@ jobs:
         solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
 
     steps:
-      - name: Run `sudo apt update -y`
-        run: sudo apt update -y  # Otherwise, free-disk-space or other actions relying on `apt` may fail
+      - name: Run `sudo apt update`
+        run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
 
       - name: Free disk space
         uses: jlumbroso/free-disk-space@main
diff --git a/.github/workflows/verify_small.yml b/.github/workflows/verify_small.yml
--- a/.github/workflows/verify_small.yml
+++ b/.github/workflows/verify_small.yml
@@ -36,8 +36,8 @@ jobs:
 
     steps:
 
-      - name: Run `sudo apt update -y`
-        run: sudo apt update -y  # Otherwise, free-disk-space or other actions relying on `apt` may fail
+      - name: Run `sudo apt update`
+        run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
 
       - name: Free disk space
         uses: jlumbroso/free-disk-space@main
