230618.003005.CST correct yml
Former-commit-id: ae7d232989984474a0ece4b087cfe31ae8f5d852

diff --git a/.github/workflows/lint_hosted.yml b/.github/workflows/lint_hosted.yml
--- a/.github/workflows/lint_hosted.yml
+++ b/.github/workflows/lint_hosted.yml
@@ -44,8 +44,8 @@ jobs:
       - name: Get fintrf.h and remove MATLAB
         if: ${{ matrix.linter == 'mlint' }}
         run: |
-          (cp ${{steps.set-up-matlab.outputs.matlabroot}}/extern/include/fintrf.h "$ROOT_DIR"/fortran/common) && (printf "Succeed!\n\n" || printf "Fail!\n\n" && exit 2)
-          sudo rm -rf ${{steps.set-up-matlab.outputs.matlabroot}} || exit 3  # Remove MATLAB, or the runner will run out of space.
+          (cp ${{steps.set-up-matlab.outputs.matlabroot}}/extern/include/fintrf.h "$ROOT_DIR"/fortran/common && printf "Succeed!\n\n") || (printf "Fail!\n\n" && exit 2)
+          sudo rm -rf ${{steps.set-up-matlab.outputs.matlabroot}}/* || exit 3  # Remove MATLAB, or the runner will run out of space.
 
       - name: Install AOCC
         run: bash .github/scripts/install_aocc
