230618.002014.CST try removing MATLAB after getting fintrf.h
Former-commit-id: 86a7985fa9af53ecec419d68c0551d6b5421d411

diff --git a/.github/workflows/lint_hosted.yml b/.github/workflows/lint_hosted.yml
--- a/.github/workflows/lint_hosted.yml
+++ b/.github/workflows/lint_hosted.yml
@@ -34,6 +34,19 @@ jobs:
       - name: Miscellaneous setup
         run: bash .github/scripts/misc_setup
 
+      - name: Set up MATLAB
+        id: set-up-matlab
+        if: ${{ matrix.linter == 'mlint' }}
+        uses: matlab-actions/setup-matlab@v2-beta
+        with:
+          release: ${{ matrix.matlab }}
+
+      - name: Get fintrf.h and remove MATLAB
+        if: ${{ matrix.linter == 'mlint' }}
+        run: |
+          (cp ${{steps.set-up-matlab.outputs.matlabroot}}/extern/include/fintrf.h "$ROOT_DIR"/fortran/common) && (printf "Succeed!\n\n" || printf "Fail!\n\n" && exit 2)
+          sudo rm -rf ${{steps.set-up-matlab.outputs.matlabroot} || exit 3  # Remove MATLAB, or the runner will run out of space.
+
       - name: Install AOCC
         run: bash .github/scripts/install_aocc
 
@@ -60,24 +73,7 @@ jobs:
       - name: Install Flang
         run: bash .github/scripts/install_flang
 
-      - name: Cache MATLAB  # N.B.: Clear the cache when the `latest` version of MATLAB changes in March and September
-        if: ${{ matrix.linter == 'mlint' }}
-        uses: actions/cache@v3.3.1
-        with:
-          path: ${{ runner.tool_cache }}/MATLAB
-          key: ${{ matrix.os }}-${{ matrix.matlab }}
-
-      - name: Set up MATLAB
-        if: ${{ matrix.linter == 'mlint' }}
-        uses: matlab-actions/setup-matlab@v2-beta
-        with:
-          release: ${{ matrix.matlab }}
-
       - name: Conduct the test
         run: |
           type gfortran ifort ifx aflang g95 nvfortran sunf95 flang
-          if [[ ${{ matrix.linter }} == "mlint" ]] ; then
-              printf "Copy fintrf to %s ...\n\n" "$ROOT_DIR"/fortran/common
-              (cp $(dirname $(which matlab))/../extern/include/fintrf.h "$ROOT_DIR"/fortran/common) && (printf "Succeed!\n\n" || printf "Fail!\n\n" && exit 2)
-          fi
           cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./${{ matrix.linter }} --all
