260215.102101.CET [skip ci] revise test_aflang to skip mtest when amdflang is not installed successfully and if the date is not a multiple of 3

diff --git a/.github/workflows/lint_hosted.yml b/.github/workflows/lint_hosted.yml
--- a/.github/workflows/lint_hosted.yml
+++ b/.github/workflows/lint_hosted.yml
@@ -91,12 +91,12 @@ jobs:
         run: bash .github/scripts/install_aocc
 
       - name: Install AOMP
-        # Retry up to 10 times with a delay of 600 seconds between retries, to avoid transient
-        # network issues. If the installation still fails after all retries, we let it fail silently
-        # and continue with the test. This is fine since there are many tests with other compilers,
-        # and since the AOMP compiler is tested in test_aflang.html. If we try too many times, there
-        # may not be enough time left for the test to run anyway!
-        run: bash .github/scripts/install_aomp 10 600 || true
+        # Retry in case of failure due to transient network issues. If the installation still fails
+        # after all retries, we let it fail silently and continue with the test. This is fine since
+        # there are many tests with other compilers, and since the AOMP compiler is tested in
+        # test_aflang.html. If we try too many times, there may not be enough time left for the test
+        # to run anyway!
+        run: bash .github/scripts/install_aomp 3 1800 || true
 
       - name: Install gfortran
         uses: fortran-lang/setup-fortran@main
diff --git a/.github/workflows/test_aflang.yml b/.github/workflows/test_aflang.yml
--- a/.github/workflows/test_aflang.yml
+++ b/.github/workflows/test_aflang.yml
@@ -66,7 +66,12 @@ jobs:
         run: bash .github/scripts/misc_setup
 
       - name: Install AOMP
-        run: bash .github/scripts/install_aomp 20 600  # Retry up to 20 times with a delay of 600 seconds between retries, to avoid transient network issues.
+        run: |
+          # Retry in case of failure due to transient network issues. If it fails and the date is
+          # not divisible by 3, then we keep going and skip the AOMP test. This is to decrease the
+          # chance of workflow failure due to transient network issues, while still testing AOMP regularly.
+          bash .github/scripts/install_aomp 8 1800 || [[ $(( $(date +%-d) % 3 )) -ne 0 ]]
+          type amdflang || echo "WARNING!!! amdflang does not work after AOMP installation, which probably failed!!!" 2>&1
 
       - name: Install AOCC
         run: bash .github/scripts/install_aocc
@@ -91,12 +96,21 @@ jobs:
           IK=i$(( 2**(1 + $(date +%-d) % 3) ))
           echo "IK=${IK}"
           echo "IK=${IK}" >> "$GITHUB_ENV"
-          cd "$ROOT_DIR"/fortran/tests && make mtest_${IK}.${{ matrix.solver }}
-          cd "$ROOT_DIR"/fortran/tests && make dtest_${IK}.${{ matrix.solver }}
 
+          if type amdflang ; then
+            cd "$ROOT_DIR"/fortran/tests && make mtest_${IK}.${{ matrix.solver }}
+            cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }}
+            export EXAMPLE_NUM=1 && make clean && make mtest
+            export EXAMPLE_NUM=2 && make clean && make mtest
+          else
+            echo "WARNING!!! amdflang does not work after AOMP installation, which probably failed!!!" 2>&1
+            echo "WARNING!!! mtest is skipped because amdflang is not available!!!" 2>& 1
+          fi
+
+          cd "$ROOT_DIR"/fortran/tests && make dtest_${IK}.${{ matrix.solver }}
           cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }}
-          export EXAMPLE_NUM=1 && make clean && make mtest && make clean && make dtest
-          export EXAMPLE_NUM=2 && make clean && make mtest && make clean && make dtest
+          export EXAMPLE_NUM=1 && make clean && make dtest
+          export EXAMPLE_NUM=2 && make clean && make dtest
 
       - name: Store artifacts
         uses: actions/upload-artifact@v6
