260219.224005.CET [skip ci] try equipez/success_on_timeout

diff --git a/.github/workflows/stress_test_fortran.yml b/.github/workflows/stress_test_fortran.yml
--- a/.github/workflows/stress_test_fortran.yml
+++ b/.github/workflows/stress_test_fortran.yml
@@ -22,7 +22,6 @@ jobs:
   test:
     name: Stress test of PRIMA on large problems
     runs-on: ${{ matrix.os }}
-    continue-on-error: true
     strategy:
       fail-fast: false
       matrix:
@@ -45,21 +44,21 @@ jobs:
 
     steps:
 
-      - name: Run `sudo apt update`
-        if: startsWith(matrix.os, 'ubuntu')
-        run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
+      # - name: Run `sudo apt update`
+      #   if: startsWith(matrix.os, 'ubuntu')
+      #   run: sudo apt update || true  # Otherwise, free-disk-space or other actions relying on `apt` may fail
 
-      - name: Free disk space
-        if: startsWith(matrix.os, 'ubuntu')
-        uses: jlumbroso/free-disk-space@main
-        with:
-          # all of these default to true, but feel free to set to "false" if necessary for your workflow
-          android: true
-          dotnet: true
-          haskell: true
-          large-packages: true
-          docker-images: true
-          swap-storage: false  # Important, or the runner may be shut down due to memory starvation.
+      # - name: Free disk space
+      #   if: startsWith(matrix.os, 'ubuntu')
+      #   uses: jlumbroso/free-disk-space@main
+      #   with:
+      #     # all of these default to true, but feel free to set to "false" if necessary for your workflow
+      #     android: true
+      #     dotnet: true
+      #     haskell: true
+      #     large-packages: true
+      #     docker-images: true
+      #     swap-storage: false  # Important, or the runner may be shut down due to memory starvation.
 
       - name: Clone Repository (Latest)
         uses: actions/checkout@v6.0.2
@@ -75,54 +74,67 @@ jobs:
           ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
           submodules: recursive
 
-      - name: Miscellaneous setup
-        run: bash .github/scripts/misc_setup
+      # - name: Miscellaneous setup
+      #   run: bash .github/scripts/misc_setup
 
-      - name: Install AOCC
-        if: ${{ matrix.compiler == 'd' }}
-        run: bash .github/scripts/install_aocc
+      # - name: Install AOCC
+      #   if: ${{ matrix.compiler == 'd' }}
+      #   run: bash .github/scripts/install_aocc
 
-      - name: Install gfortran
-        if: ${{ matrix.compiler == 'g' }}
-        uses: fortran-lang/setup-fortran@main
-        id: setup-fortran
-        with:
-          compiler: gcc
+      # - name: Install gfortran
+      #   if: ${{ matrix.compiler == 'g' }}
+      #   uses: fortran-lang/setup-fortran@main
+      #   id: setup-fortran
+      #   with:
+      #     compiler: gcc
 
-      - name: Install Intel oneAPI on Linux
-        if: ${{ startsWith(matrix.os, 'ubuntu') && (matrix.compiler == 'i' || matrix.compiler == 'x') }}
-        run: bash .github/scripts/install_oneapi_linux.sh
+      # - name: Install Intel oneAPI on Linux
+      #   if: ${{ startsWith(matrix.os, 'ubuntu') && (matrix.compiler == 'i' || matrix.compiler == 'x') }}
+      #   run: bash .github/scripts/install_oneapi_linux.sh
 
-      - name: Install Intel oneAPI on macOS
-        if: ${{ startsWith(matrix.os, 'macos') && (matrix.compiler == 'i' || matrix.compiler == 'x') }}
-        run: bash .github/scripts/install_oneapi_macos.sh
+      # - name: Install Intel oneAPI on macOS
+      #   if: ${{ startsWith(matrix.os, 'macos') && (matrix.compiler == 'i' || matrix.compiler == 'x') }}
+      #   run: bash .github/scripts/install_oneapi_macos.sh
 
-      - name: Install nvfortran
-        if: ${{ matrix.compiler == 'v' }}
-        run: bash .github/scripts/install_nvfortran
+      # - name: Install nvfortran
+      #   if: ${{ matrix.compiler == 'v' }}
+      #   run: bash .github/scripts/install_nvfortran
 
-      - name: Install Oracle sunf95
-        if: ${{ matrix.compiler == 's' }}
-        run: bash .github/scripts/install_sunf95
+      # - name: Install Oracle sunf95
+      #   if: ${{ matrix.compiler == 's' }}
+      #   run: bash .github/scripts/install_sunf95
 
-      # Install Flang after AOCC, to make sure that flang is this one, while AOCC flang will be
-      # known as aoccflang.
-      - name: Install Flang
-        if: ${{ matrix.compiler == 'f' }}
-        run: bash .github/scripts/install_llvm
+      # # Install Flang after AOCC, to make sure that flang is this one, while AOCC flang will be
+      # # known as aoccflang.
+      # - name: Install Flang
+      #   if: ${{ matrix.compiler == 'f' }}
+      #   run: bash .github/scripts/install_llvm
 
-      - name: Conduct the test
-        run: |
-          cd "$ROOT_DIR"/fortran/tests
-          export TESTDIM=${{ matrix.testdim }}
-          RK=$((2**($(date +%-d) % 3 + 2)))
-          if [[ $RK==16 && dfrv == *${{ matrix.compiler }}* ]] ; then
-              echo "r16 test is skipped for compiler " ${{ matrix.compiler }}
-              echo "Test r8 instead"
-              RK=8
-          fi
-          echo "RK = " $RK
-          make ${{ matrix.compiler }}test_i2_r${RK}_d1_tst.${{ matrix.solver }}
+      - name: Conduct the test; treat timeout as SUCCESS (exit 0)
+          uses: equipez/success-on-timeout@v1
+          with:
+          time: 10s
+          command: |
+            cd "$ROOT_DIR"/fortran/tests
+            export TESTDIM=${{ matrix.testdim }}
+            RK=$((2**($(date +%-d) % 3 + 2)))
+            if [[ $RK==16 && dfrv == *${{ matrix.compiler }}* ]] ; then
+                echo "r16 test is skipped for compiler " ${{ matrix.compiler }}
+                echo "Test r8 instead"
+                RK=8
+            fi
+            echo "RK = " $RK
+            # Sleep for R seconds, with R being a random integer between 1 and 20, to simulate the
+            # test running time. The actual test command is commented out for now, as it may take
+            # a long time to run and may cause the workflow to be canceled due to overtime.
+            R=$((RANDOM % 20 + 1))
+            echo "Simulating the test running time by sleeping for $R seconds..."
+            sleep $R
+            # Use modulo(R, 2) as the exit code, to simulate the test passing or failing randomly.
+            EXIT_CODE=$((R % 2))
+            echo "Exiting with code $EXIT_CODE..."
+            exit $EXIT_CODE
+            #make ${{ matrix.compiler }}test_i2_r${RK}_d1_tst.${{ matrix.solver }}
 
       - name: Store artifacts
         uses: actions/upload-artifact@v6
@@ -134,20 +146,3 @@ jobs:
       - name: Remove the test data
         if: always()  # Always run even if the workflow is canceled manually or due to overtime.
         run: rm -rf ${{ env.TEST_DIR }}
-
-  # The following job check whether the tests were successful or cancelled due to timeout.
-  # N.B.: Remember to specify `continue-on-error: true` for the job of the tests.
-  check_success_timeout:
-    runs-on: ubuntu-latest
-    if: ${{ !cancelled() }}
-    needs: test
-    steps:
-      - name: Clone the GitHub actions scripts
-        uses: actions/checkout@v6.0.2
-        with:
-          repository: equipez/github_actions_scripts
-          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
-          path: scripts
-
-      - name: Check whether the tests were successful or cancelled due to timeout
-        run: bash scripts/check_success_timeout ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.run_id }}
