260219.232730.CET [skip ci] try stress_test_fortran.yml with timeout 1m, with AOMP and ATfL installed

diff --git a/.github/workflows/stress_test_fortran.yml b/.github/workflows/stress_test_fortran.yml
--- a/.github/workflows/stress_test_fortran.yml
+++ b/.github/workflows/stress_test_fortran.yml
@@ -115,6 +115,19 @@ jobs:
         if: ${{ matrix.compiler == 'd' }}
         run: bash .github/scripts/install_aocc
 
+      - name: Install AOMP
+        if: ${{ matrix.compiler == 'm' }}
+        # Retry in case of failure due to transient network issues. If the installation still fails
+        # after all retries, we let it fail silently and continue with the test. This is fine since
+        # there are many tests with other compilers, and since the AOMP compiler is tested in
+        # test_aflang.html. If we try too many times, there may not be enough time left for the test
+        # to run anyway!
+        run: bash .github/scripts/install_aomp 3 1800 || true
+
+      - name: Install Arm Toolchain for Linux
+        if: ${{ matrix.compiler == 'r' }}
+        run: bash .github/scripts/install_atfl
+
       - name: Install gfortran
         if: ${{ matrix.compiler == 'g' }}
         uses: fortran-lang/setup-fortran@main
