260203.061636.CET [skip ci] revise install_armflang and test_armflang.yml to exit 0 if the compiler is not installed successfully

diff --git a/.github/workflows/test_armflang.yml b/.github/workflows/test_armflang.yml
--- a/.github/workflows/test_armflang.yml
+++ b/.github/workflows/test_armflang.yml
@@ -66,7 +66,8 @@ jobs:
         run: bash .github/scripts/misc_setup
 
       - name: Install Arm Fortran compiler
-        run: bash .github/scripts/install_armflang
+        run: bash .github/scripts/install_armflang || { echo "Warning: Arm Fortran compiler installation failed! The test will be skipped." >&2; }
+        # Exit code 0 even if the installation fails. The test will be skipped later.
 
       - name: Revise bobyqa/trustregion.f90 to see why `xbdi(trueloc(xopt >= su .and. gopt <= 0)) = 1` leads to a SIGFPE
         shell: bash
@@ -77,6 +78,7 @@ jobs:
 
       - name: Conduct the test
         run: |
+          command -v armflang || { echo "Warning: Arm Fortran compiler not found! The installation probably failed. Skip the test." >&2; exit 0; }
           cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./flint -r && bash ./mlint -r
           export FFLAGS=${{ matrix.fflags }}
           export TESTDIM=${{ matrix.testdim }}
